// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQcteuo3I138Rn95mCgJ-XsFWspRsT664',
    appId: '1:1021038287531:android:71c2a84b13b92a3118f5ee',
    messagingSenderId: '1021038287531',
    projectId: 'buscord-1bb38',
    databaseURL: 'https://buscord-1bb38-default-rtdb.firebaseio.com',
    storageBucket: 'buscord-1bb38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCd3d1zYGXxE1gknlhqPLx4z1yPNLazq0',
    appId: '1:1021038287531:ios:5697bee5fc20724218f5ee',
    messagingSenderId: '1021038287531',
    projectId: 'buscord-1bb38',
    databaseURL: 'https://buscord-1bb38-default-rtdb.firebaseio.com',
    storageBucket: 'buscord-1bb38.appspot.com',
    iosClientId: '1021038287531-i1d89tntdh555ob4b8fru0b60u3gjlno.apps.googleusercontent.com',
    iosBundleId: 'com.example.proyectoCarnes',
  );
}
